[tool.poetry]
name = "seguid"
version = "0.0.3.9007"
description = "Sequence Globally Unique Identifier (SEGUID) Checksums for Linear, Circular, Single-Stranded and Double-Stranded Biological Sequences"
authors = ["BjornFJohansson <bjornjobb@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.3, <4.0"
pydivsufsort = { version = "^0.0.14", optional = true }

[tool.poetry.extras]
pydivsufsort =  ["pydivsufsort"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
