on: [push, pull_request]

name: "CLI check"

permissions:
  contents: read

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install this Python package
      run: |
        pip install .[pydivsufsort]

    - name: Session information
      run: |
        python --version

    - name: Check CLI
      if: runner.os != 'Windows'
      run: |
        curl -L -O https://github.com/bats-core/bats-core/archive/refs/tags/v1.10.0.tar.gz && tar xf v1.10.0.tar.gz
        export PATH=$PWD/bats-core-1.10.0/bin:$PATH
        bash --version
        bats --version
        mkdir tmp
        cd tmp
        curl -L -O https://raw.githubusercontent.com/seguid/seguid-tests/main/Makefile
        make check-cli/seguid-python

