name: Build for PyPI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'main'
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.SEGUID_PYPI_TOKEN }}
          plugins: "poetry-dynamic-versioning[plugin]"
