on: [push, pull_request]

name: "seguid-tests"

permissions:
  contents: read

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install this Python package
      run: |
        pip install .[pydivsufsort]

    - name: Session information
      run: python --version

    - name: Check CLI
      if: runner.os != 'Windows'
      run: make check-cli

    - name: Check API
      run: make check-api
