on: [push, pull_request]

name: "test-coverage"

permissions:
  contents: read

jobs:
  test-coverage:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Install this Python package
      run: |
        pip install .[pydivsufsort]

    - name: Session information
      run: |
        python --version

    - name: Generate coverage report
      run: |
        pip install pytest-cov
        pytest --cov=./ ## output summarize in GitHub logs
        pytest --cov=./ --cov-report=xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,PYTHON
        files: coverage.xml
        fail_ci_if_error: true
        flags: unittests
        name: codecov-umbrella
        verbose: true
